name: Deploy PWA to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup for GitHub Pages
        run: |
          cp public/manifest.gh.json public/manifest.json
          cp public/sw.gh.js public/sw.js
      - name: Deploy public/ to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
